### ISSUE TITLE
Can't import project to Monaca

### ISSUE THREAD

**Issue by trknov** [monaca/sample-twitter-client#1]
Can't import project to Monaca.
Error displayed:

> Internal Server Error (500)
> Neither project_info.json nor config.xml was found. Maybe an old project?

The same happens when I import by URL or when I select from my forked projects.

![image](https://cloud.githubusercontent.com/assets/2579783/18834055/871a58ac-83fc-11e6-8483-6a6af5c4c7de.png)

**Comment by masahirotanaka** [comment]
@ttarakanoff Sorry for being late. Can you please try the following one: https://docs.monaca.io/en/sampleapp/samples/twitter/?
We renewed Twitter app sample, and the one above should work.

**Comment by trknov** [comment]
Ok, thanks, this one works well.
